drop table PAYMENTENTITY_ITEMENTITY;
drop table ARTWORKENTITY_CATEGORYENTITY;
drop table QUALIFICATIONENTITY;
drop table ITEMENTITY;
drop table COMMENTENTITY;
drop table ARTWORKENTITY;
drop table ARTISTENTITY;
drop table PRODUCTENTITY;
drop table PAYMENTENTITY;
drop table CLIENTENTITY;
drop table CATEGORYENTITY;

DELETE FROM PAYMENTENTITY_ITEMENTITY;
DELETE FROM ARTWORKENTITY_CATEGORYENTITY;
DELETE FROM QUALIFICATIONENTITY;
DELETE FROM ITEMENTITY;
DELETE FROM COMMENTENTITY;
DELETE FROM ARTWORKENTITY;
DELETE FROM ARTISTENTITY;
DELETE FROM PRODUCTENTITY;
DELETE FROM PAYMENTENTITY;
DELETE FROM CLIENTENTITY;
DELETE FROM CATEGORYENTITY;

insert into ARTISTENTITY (name, username) values ('Cynthia Hamilton','artist1');
insert into ARTISTENTITY (name, username) values ('Harold Moreno','artist2');
insert into ARTISTENTITY (name, username) values ('Virginia Cunningham','artist3');
insert into ARTISTENTITY (name, username) values ('Patrick Bailey','artist4');
insert into ARTISTENTITY (name, username) values ('Judith Matthews','artist5');
insert into ARTISTENTITY (name, username) values ('Jacqueline White','artist6');
insert into ARTISTENTITY (name, username) values ('Gloria Henderson','artist7');
insert into ARTISTENTITY (name, username) values ('Robert Gibson','artist8');
insert into ARTISTENTITY (name, username) values ('Jennifer Gomez','artist9');
insert into ARTISTENTITY (name, username) values ('Robin Gomez','artist10');



insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Viva', 3094612, 9, 458, 304, 'https://unsplash.it/304/458?image=1');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Aerified', 8900110, 1, 419, 382, 'https://unsplash.it/382/419?image=9');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Greenlam', 663147, 9, 308, 264, 'https://unsplash.it/264/308?image=17');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Asoka', 9029116, 2, 305, 271, 'https://unsplash.it/271/305?image=25');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Span', 8571733, 4, 448, 326, 'https://unsplash.it/326/448?image=33');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Duobam', 907394, 8, 386, 356, 'https://unsplash.it/356/386?image=41');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Home Ing', 9780736, 9, 478, 335, 'https://unsplash.it/335/478?image=49');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Regrant', 348509, 1, 308, 243, 'https://unsplash.it/243/308?image=57');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Quo Lux', 4209708, 2, 385, 276, 'https://unsplash.it/276/385?image=65');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Daltfresh', 7174232, 5, 441, 234, 'https://unsplash.it/234/441?image=73');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Otcom', 5666982, 10, 345, 399, 'https://unsplash.it/399/345?image=81');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Lotlux', 4755837, 10, 451, 325, 'https://unsplash.it/325/451?image=89');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Tres-Zap', 4316422, 7, 477, 245, 'https://unsplash.it/245/477?image=97');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Aerified', 7352881, 9, 424, 306, 'https://unsplash.it/306/424?image=105');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Bitwolf', 4388822, 8, 427, 394, 'https://unsplash.it/394/427?image=113');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Transcof', 5857965, 1, 425, 287, 'https://unsplash.it/287/425?image=121');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Voyatouch', 2415164, 6, 410, 291, 'https://unsplash.it/291/410?image=129');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Opela', 9111379, 3, 492, 217, 'https://unsplash.it/217/492?image=137');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Gembucket', 6860663, 2, 443, 285, 'https://unsplash.it/285/443?image=145');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Keylex', 7776724, 4, 328, 260, 'https://unsplash.it/260/328?image=153');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Trippledex', 9103491, 1, 476, 232, 'https://unsplash.it/232/476?image=161');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Regrant', 7305797, 1, 368, 313, 'https://unsplash.it/313/368?image=169');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Konklux', 4653515, 10, 348, 350, 'https://unsplash.it/350/348?image=177');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Y-find', 4156798, 3, 414, 311, 'https://unsplash.it/311/414?image=185');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Mat Lam Tam', 9331736, 10, 351, 205, 'https://unsplash.it/205/351?image=193');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Latlux', 2468774, 5, 483, 297, 'https://unsplash.it/297/483?image=201');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Alphazap', 2811265, 2, 489, 255, 'https://unsplash.it/255/489?image=209');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Lotlux', 4520392, 10, 430, 318, 'https://unsplash.it/318/430?image=217');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Fixflex', 4017302, 8, 368, 212, 'https://unsplash.it/212/368?image=225');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Job', 5819766, 2, 421, 339, 'https://unsplash.it/339/421?image=233');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Opela', 4198937, 6, 409, 363, 'https://unsplash.it/363/409?image=241');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Zathin', 9596418, 8, 372, 287, 'https://unsplash.it/287/372?image=249');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Daltfresh', 5232734, 8, 494, 305, 'https://unsplash.it/305/494?image=257');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Quo Lux', 6662761, 3, 448, 213, 'https://unsplash.it/213/448?image=265');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Zamit', 9418129, 5, 496, 288, 'https://unsplash.it/288/496?image=273');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Sonair', 6046241, 7, 466, 364, 'https://unsplash.it/364/466?image=281');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Konklab', 4916873, 9, 475, 373, 'https://unsplash.it/373/475?image=289');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Zontrax', 9308056, 9, 426, 233, 'https://unsplash.it/233/426?image=297');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Duobam', 973076, 7, 457, 358, 'https://unsplash.it/358/457?image=305');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Sonsing', 6441178, 1, 468, 218, 'https://unsplash.it/218/468?image=313');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Trippledex', 8117396, 2, 404, 337, 'https://unsplash.it/337/404?image=321');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Trippledex', 9320884, 5, 314, 230, 'https://unsplash.it/230/314?image=329');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Andalax', 4007186, 2, 382, 218, 'https://unsplash.it/218/382?image=337');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Gembucket', 3917933, 2, 445, 254, 'https://unsplash.it/254/445?image=345');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Treeflex', 2799197, 3, 386, 378, 'https://unsplash.it/378/386?image=353');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Stronghold', 2036789, 1, 442, 243, 'https://unsplash.it/243/442?image=361');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Ronstring', 6460604, 10, 469, 340, 'https://unsplash.it/340/469?image=369');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Viva', 872934, 3, 305, 260, 'https://unsplash.it/260/305?image=377');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Stringtough', 7054370, 8, 404, 233, 'https://unsplash.it/233/404?image=385');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Job', 7755364, 10, 476, 336, 'https://unsplash.it/336/476?image=393');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Kanlam', 958058, 4, 498, 379, 'https://unsplash.it/379/498?image=401');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Gembucket', 7651194, 5, 370, 361, 'https://unsplash.it/361/370?image=409');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Matsoft', 6684148, 2, 334, 308, 'https://unsplash.it/308/334?image=417');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Kanlam', 1241679, 2, 493, 249, 'https://unsplash.it/249/493?image=425');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Konklux', 2510834, 9, 309, 380, 'https://unsplash.it/380/309?image=433');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Opela', 9734886, 2, 327, 347, 'https://unsplash.it/347/327?image=441');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Voltsillam', 1652740, 9, 332, 313, 'https://unsplash.it/313/332?image=449');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Holdlamis', 351352, 5, 492, 265, 'https://unsplash.it/265/492?image=457');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Prodder', 7270437, 5, 366, 389, 'https://unsplash.it/389/366?image=465');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Cookley', 6492441, 4, 333, 205, 'https://unsplash.it/205/333?image=473');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Domainer', 4045195, 3, 500, 223, 'https://unsplash.it/223/500?image=481');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Overhold', 2520854, 5, 305, 316, 'https://unsplash.it/316/305?image=489');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Mat Lam Tam', 1365454, 1, 475, 269, 'https://unsplash.it/269/475?image=497');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Overhold', 7732767, 4, 478, 299, 'https://unsplash.it/299/478?image=505');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Gembucket', 3842394, 1, 498, 379, 'https://unsplash.it/379/498?image=513');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Vagram', 6237328, 5, 460, 274, 'https://unsplash.it/274/460?image=521');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Tin', 9710412, 3, 420, 302, 'https://unsplash.it/302/420?image=529');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Flowdesk', 3486766, 3, 312, 315, 'https://unsplash.it/315/312?image=537');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Y-Solowarm', 2799578, 10, 467, 265, 'https://unsplash.it/265/467?image=545');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Bitwolf', 1896642, 3, 451, 231, 'https://unsplash.it/231/451?image=553');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Aerified', 6771812, 8, 388, 343, 'https://unsplash.it/343/388?image=561');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Kanlam', 2068035, 3, 402, 328, 'https://unsplash.it/328/402?image=569');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Bitchip', 4856410, 3, 428, 329, 'https://unsplash.it/329/428?image=577');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Solarbreeze', 9344863, 10, 326, 240, 'https://unsplash.it/240/326?image=585');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Cardify', 9411977, 9, 304, 240, 'https://unsplash.it/240/304?image=593');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Sonsing', 3774567, 2, 334, 233, 'https://unsplash.it/233/334?image=601');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Alphazap', 6371656, 7, 322, 392, 'https://unsplash.it/392/322?image=609');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Tresom', 9536739, 9, 361, 258, 'https://unsplash.it/258/361?image=617');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Andalax', 4129803, 7, 422, 266, 'https://unsplash.it/266/422?image=625');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Opela', 9658338, 9, 459, 245, 'https://unsplash.it/245/459?image=633');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Sonair', 1917457, 7, 309, 247, 'https://unsplash.it/247/309?image=641');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Otcom', 2360457, 6, 424, 246, 'https://unsplash.it/246/424?image=649');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Keylex', 840036, 5, 456, 383, 'https://unsplash.it/383/456?image=657');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Fixflex', 799583, 3, 372, 224, 'https://unsplash.it/224/372?image=665');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Y-find', 4770141, 6, 350, 236, 'https://unsplash.it/236/350?image=673');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Hatity', 1761467, 9, 300, 394, 'https://unsplash.it/394/300?image=681');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Ronstring', 7178608, 4, 417, 352, 'https://unsplash.it/352/417?image=689');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Gembucket', 8341372, 1, 364, 245, 'https://unsplash.it/245/364?image=697');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Latlux', 4467728, 5, 370, 305, 'https://unsplash.it/305/370?image=705');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Matsoft', 5821191, 9, 382, 287, 'https://unsplash.it/287/382?image=713');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Flowdesk', 1175430, 9, 480, 243, 'https://unsplash.it/243/480?image=721');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Tres-Zap', 7188208, 4, 357, 298, 'https://unsplash.it/298/357?image=729');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Holdlamis', 8131164, 9, 311, 365, 'https://unsplash.it/365/311?image=737');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Asoka', 1954033, 5, 397, 392, 'https://unsplash.it/392/397?image=745');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Zontrax', 5912335, 8, 395, 380, 'https://unsplash.it/380/395?image=753');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Regrant', 9281307, 7, 409, 376, 'https://unsplash.it/376/409?image=761');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Rank', 1404432, 6, 308, 329, 'https://unsplash.it/329/308?image=769');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Wrapsafe', 7675416, 10, 418, 368, 'https://unsplash.it/368/418?image=777');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('It', 7660801, 9, 321, 282, 'https://unsplash.it/282/321?image=785');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Fix San', 8556981, 7, 450, 348, 'https://unsplash.it/348/450?image=793');




INSERT INTO CATEGORYENTITY(name) values('Ceramica');
INSERT INTO CATEGORYENTITY(name) values('Dibujo');
INSERT INTO CATEGORYENTITY(name) values('Escultura');
INSERT INTO CATEGORYENTITY(name) values('Grabado');
INSERT INTO CATEGORYENTITY(name) values('Mosaico');
INSERT INTO CATEGORYENTITY(name) values('Obra pictorica');




insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (1, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (2, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (3, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (4, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (5, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (6, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (7, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (8, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (9, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (10, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (11, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (12, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (13, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (14, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (15, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (16, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (17, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (18, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (19, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (20, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (21, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (22, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (23, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (24, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (25, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (26, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (27, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (28, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (29, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (30, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (31, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (32, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (33, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (34, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (35, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (36, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (37, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (38, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (39, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (40, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (41, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (42, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (43, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (44, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (45, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (46, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (47, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (48, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (49, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (50, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (51, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (52, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (53, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (54, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (55, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (56, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (57, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (58, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (59, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (60, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (61, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (62, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (63, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (64, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (65, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (66, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (67, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (68, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (69, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (70, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (71, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (72, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (73, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (74, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (75, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (76, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (77, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (78, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (79, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (80, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (81, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (82, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (83, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (84, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (85, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (86, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (87, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (88, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (89, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (90, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (91, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (92, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (93, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (94, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (95, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (96, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (97, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (98, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (99, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (100, 6);




insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', null, 100);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', null, 53);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras in purus eu magna vulputate luctus.', null, 22);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Phasellus in felis.', null, 2);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aliquam non mauris. Morbi non lectus.', null, 68);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec ut dolor.', null, 12);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', null, 49);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', null, 24);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce consequat. Nulla nisl.', null, 7);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', null, 73);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nam nulla.', null, 16);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', null, 75);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aliquam erat volutpat. In congue.', null, 96);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aliquam non mauris. Morbi non lectus.', null, 72);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', null, 66);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', null, 22);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', null, 5);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', null, 4);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', null, 100);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', null, 100);
insert into COMMENTENTITY (comment, name, artwork_id) values ('In hac habitasse platea dictumst.', null, 69);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aenean lectus. Pellentesque eget nunc.', null, 14);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent id massa id nisl venenatis lacinia.', null, 89);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent id massa id nisl venenatis lacinia.', null, 78);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', null, 57);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent blandit. Nam nulla.', null, 76);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', null, 47);
insert into COMMENTENTITY (comment, name, artwork_id) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna.', null, 82);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', null, 64);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', null, 43);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Etiam pretium iaculis justo. In hac habitasse platea dictumst.', null, 8);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Mauris lacinia sapien quis libero.', null, 13);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus vel nulla eget eros elementum pellentesque.', null, 28);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis mattis egestas metus. Aenean fermentum.', null, 13);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', null, 16);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', null, 71);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Maecenas rhoncus aliquam lacus.', null, 33);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', null, 48);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce consequat.', null, 10);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', null, 2);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Etiam pretium iaculis justo. In hac habitasse platea dictumst.', null, 53);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Pellentesque ultrices mattis odio. Donec vitae nisi.', null, 29);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec dapibus.', null, 59);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nulla mollis molestie lorem. Quisque ut erat.', null, 10);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', null, 12);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Maecenas pulvinar lobortis est.', null, 35);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras non velit nec nisi vulputate nonummy.', null, 19);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', null, 97);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nulla mollis molestie lorem.', null, 75);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce posuere felis sed lacus.', null, 75);
insert into COMMENTENTITY (comment, name, artwork_id) values ('In hac habitasse platea dictumst.', null, 100);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Phasellus in felis.', null, 7);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis consequat dui nec nisi volutpat eleifend.', null, 53);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', null, 47);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec semper sapien a libero. Nam dui.', null, 91);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', null, 35);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', null, 30);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', null, 80);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', null, 87);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras pellentesque volutpat dui.', null, 35);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', null, 82);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', null, 80);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Ut tellus.', null, 54);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', null, 48);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent blandit lacinia erat.', null, 17);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', null, 22);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nam nulla.', null, 1);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus tortor. Duis mattis egestas metus.', null, 92);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Suspendisse potenti.', null, 94);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nulla suscipit ligula in lacus.', null, 14);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi quis tortor id nulla ultrices aliquet.', null, 93);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec quis orci eget orci vehicula condimentum.', null, 57);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', null, 17);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum rutrum rutrum neque.', null, 10);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent blandit. Nam nulla.', null, 55);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce consequat. Nulla nisl.', null, 1);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec semper sapien a libero.', null, 95);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec posuere metus vitae ipsum. Aliquam non mauris.', null, 40);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Quisque ut erat.', null, 28);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras in purus eu magna vulputate luctus.', null, 53);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', null, 1);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Suspendisse potenti.', null, 73);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi a ipsum. Integer a nibh.', null, 95);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus vestibulum sagittis sapien.', null, 8);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', null, 54);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Phasellus sit amet erat.', null, 49);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', null, 58);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer ac neque. Duis bibendum.', null, 2);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Etiam vel augue.', null, 49);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', null, 17);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', null, 45);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Sed accumsan felis. Ut at dolor quis odio consequat varius.', null, 21);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', null, 75);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis at velit eu est congue elementum.', null, 93);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Suspendisse potenti. Nullam porttitor lacus at turpis.', null, 48);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Etiam justo. Etiam pretium iaculis justo.', null, 80);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', null, 9);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', null, 22);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Pellentesque viverra pede ac diam.', null, 70);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Ut at dolor quis odio consequat varius.', null, 2);


insert into cliententity values(1,'test');
insert into cliententity values(101,'cliente');




insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 1);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 2);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 3);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 4);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 5);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 6);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 7);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 8);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 9);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 10);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 11);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 12);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 13);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 14);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 15);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 16);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 17);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 18);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 19);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 20);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 21);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 22);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 23);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 24);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 25);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 26);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 27);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 28);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 29);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 30);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 31);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 32);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 33);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 34);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 35);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 36);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 37);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 38);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 39);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 40);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 41);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 42);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 43);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 44);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 45);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 46);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 47);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 48);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 49);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 50);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 51);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 52);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 53);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 54);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 55);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 56);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 57);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 58);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 59);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 60);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 61);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 62);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 63);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 64);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 65);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 66);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 67);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 68);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 69);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 70);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 71);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 72);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 73);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 74);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 75);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 76);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 77);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 78);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 79);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 80);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 81);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 82);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 83);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 84);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 85);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 86);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 87);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 88);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 89);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 90);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 91);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 92);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 93);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 94);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 95);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 96);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 97);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 98);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 99);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 100);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 1);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 2);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 3);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 4);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 5);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 6);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 7);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 8);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 9);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 10);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 11);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 12);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 13);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 14);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 15);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 16);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 17);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 18);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 19);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 20);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 21);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 22);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 23);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 24);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 25);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 26);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 27);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 28);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 29);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 30);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 31);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 32);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 33);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 34);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 35);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 36);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 37);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 38);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 39);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 40);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 41);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 42);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 43);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 44);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 45);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 46);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 47);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 48);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 49);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 50);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 51);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 52);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 53);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 54);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 55);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 56);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 57);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 58);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 59);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 60);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 61);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 62);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 63);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 64);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 65);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 66);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 67);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 68);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 69);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 70);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 71);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 72);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 73);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 74);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 75);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 76);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 77);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 78);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 79);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 80);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 81);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 82);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 83);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 84);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 85);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 86);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 87);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 88);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 89);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 90);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 91);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 92);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 93);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 94);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 95);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 96);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 97);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 98);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 99);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 100);