DELETE FROM PAYMENTENTITY_ITEMENTITY;
DELETE FROM ARTWORKENTITY_CATEGORYENTITY;
DELETE FROM QUALIFICATIONENTITY;
DELETE FROM ITEMENTITY;
DELETE FROM COMMENTENTITY;
DELETE FROM ARTWORKENTITY;
DELETE FROM ARTISTENTITY;
DELETE FROM PRODUCTENTITY;
DELETE FROM PAYMENTENTITY;
DELETE FROM CLIENTENTITY;
DELETE FROM CATEGORYENTITY;

insert into ARTISTENTITY (name) values ('Cynthia Hamilton');
insert into ARTISTENTITY (name) values ('Harold Moreno');
insert into ARTISTENTITY (name) values ('Virginia Cunningham');
insert into ARTISTENTITY (name) values ('Patrick Bailey');
insert into ARTISTENTITY (name) values ('Judith Matthews');
insert into ARTISTENTITY (name) values ('Jacqueline White');
insert into ARTISTENTITY (name) values ('Gloria Henderson');
insert into ARTISTENTITY (name) values ('Robert Gibson');
insert into ARTISTENTITY (name) values ('Jennifer Gomez');
insert into ARTISTENTITY (name) values ('Robin Gomez');
insert into ARTISTENTITY (name) values ('Jacqueline Carr');
insert into ARTISTENTITY (name) values ('Ruby Fox');
insert into ARTISTENTITY (name) values ('Benjamin Stanley');
insert into ARTISTENTITY (name) values ('Jerry Wright');
insert into ARTISTENTITY (name) values ('Christine Ford');
insert into ARTISTENTITY (name) values ('Peter Jones');
insert into ARTISTENTITY (name) values ('Jeffrey Porter');
insert into ARTISTENTITY (name) values ('Donna Pierce');
insert into ARTISTENTITY (name) values ('Mark Meyer');
insert into ARTISTENTITY (name) values ('Kimberly James');




insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Redhold', 3457522, 14, 369, 226, 'https://unsplash.it/226/369?image=1');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Viva', 6383712, 7, 319, 283, 'https://unsplash.it/283/319?image=9');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Fixflex', 676403, 11, 486, 229, 'https://unsplash.it/229/486?image=17');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Mat Lam Tam', 3274871, 2, 301, 203, 'https://unsplash.it/203/301?image=25');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Redhold', 5180805, 15, 412, 270, 'https://unsplash.it/270/412?image=33');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Sonsing', 116520, 18, 322, 345, 'https://unsplash.it/345/322?image=41');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Gembucket', 1279677, 6, 350, 306, 'https://unsplash.it/306/350?image=49');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Greenlam', 3927386, 9, 398, 246, 'https://unsplash.it/246/398?image=57');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Home Ing', 9937121, 20, 346, 227, 'https://unsplash.it/227/346?image=65');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Otcom', 4143246, 18, 358, 370, 'https://unsplash.it/370/358?image=73');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Bigtax', 7339451, 11, 406, 207, 'https://unsplash.it/207/406?image=81');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Bitwolf', 5620588, 12, 331, 311, 'https://unsplash.it/311/331?image=89');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Lotstring', 7944246, 16, 483, 247, 'https://unsplash.it/247/483?image=97');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Alpha', 7892426, 20, 470, 232, 'https://unsplash.it/232/470?image=105');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Hatity', 6998563, 6, 341, 330, 'https://unsplash.it/330/341?image=113');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('It', 9305646, 19, 324, 277, 'https://unsplash.it/277/324?image=121');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Zontrax', 6367564, 8, 418, 268, 'https://unsplash.it/268/418?image=129');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Wrapsafe', 2796398, 9, 316, 358, 'https://unsplash.it/358/316?image=137');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Quo Lux', 7638615, 14, 398, 237, 'https://unsplash.it/237/398?image=145');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Veribet', 2534654, 13, 402, 252, 'https://unsplash.it/252/402?image=153');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Duobam', 9843006, 4, 404, 346, 'https://unsplash.it/346/404?image=161');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Sub-Ex', 1432529, 8, 433, 201, 'https://unsplash.it/201/433?image=169');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Home Ing', 7310942, 9, 427, 369, 'https://unsplash.it/369/427?image=177');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Sub-Ex', 6598911, 6, 382, 337, 'https://unsplash.it/337/382?image=185');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Overhold', 7858972, 9, 311, 278, 'https://unsplash.it/278/311?image=193');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Ventosanzap', 4293496, 13, 418, 243, 'https://unsplash.it/243/418?image=201');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Domainer', 7768004, 4, 313, 230, 'https://unsplash.it/230/313?image=209');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Matsoft', 8804351, 8, 390, 373, 'https://unsplash.it/373/390?image=217');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Vagram', 7335202, 19, 459, 320, 'https://unsplash.it/320/459?image=225');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Konklux', 6299299, 18, 392, 309, 'https://unsplash.it/309/392?image=233');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Hatity', 5385524, 3, 349, 321, 'https://unsplash.it/321/349?image=241');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Latlux', 4333877, 17, 477, 266, 'https://unsplash.it/266/477?image=249');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Latlux', 1459677, 1, 370, 315, 'https://unsplash.it/315/370?image=257');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Home Ing', 2457573, 4, 470, 206, 'https://unsplash.it/206/470?image=265');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Asoka', 4495007, 10, 472, 307, 'https://unsplash.it/307/472?image=273');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Ronstring', 6971515, 17, 382, 283, 'https://unsplash.it/283/382?image=281');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Y-Solowarm', 9932187, 3, 448, 339, 'https://unsplash.it/339/448?image=289');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Biodex', 1059380, 17, 332, 320, 'https://unsplash.it/320/332?image=297');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Namfix', 8263472, 5, 498, 232, 'https://unsplash.it/232/498?image=305');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Stim', 1103932, 15, 344, 398, 'https://unsplash.it/398/344?image=313');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Wrapsafe', 7649896, 9, 360, 338, 'https://unsplash.it/338/360?image=321');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Lotstring', 6073142, 7, 462, 248, 'https://unsplash.it/248/462?image=329');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Sonsing', 7784738, 19, 402, 241, 'https://unsplash.it/241/402?image=337');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Cookley', 3178718, 12, 361, 336, 'https://unsplash.it/336/361?image=345');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Flexidy', 3444868, 13, 490, 249, 'https://unsplash.it/249/490?image=353');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Voltsillam', 6101870, 12, 466, 207, 'https://unsplash.it/207/466?image=361');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Zamit', 7331645, 14, 330, 296, 'https://unsplash.it/296/330?image=369');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Domainer', 8671518, 16, 427, 262, 'https://unsplash.it/262/427?image=377');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Cookley', 4343817, 7, 342, 213, 'https://unsplash.it/213/342?image=385');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Quo Lux', 221337, 7, 427, 241, 'https://unsplash.it/241/427?image=393');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Konklux', 2617301, 11, 338, 240, 'https://unsplash.it/240/338?image=401');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Lotstring', 3267536, 3, 381, 228, 'https://unsplash.it/228/381?image=409');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Namfix', 8644155, 20, 336, 340, 'https://unsplash.it/340/336?image=417');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Namfix', 3646554, 3, 453, 392, 'https://unsplash.it/392/453?image=425');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Viva', 3160219, 4, 330, 335, 'https://unsplash.it/335/330?image=433');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Ventosanzap', 4228557, 2, 409, 305, 'https://unsplash.it/305/409?image=441');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Namfix', 2604986, 3, 384, 365, 'https://unsplash.it/365/384?image=449');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Tin', 8020838, 2, 336, 393, 'https://unsplash.it/393/336?image=457');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Ronstring', 3168399, 13, 315, 315, 'https://unsplash.it/315/315?image=465');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Stronghold', 3359562, 9, 351, 361, 'https://unsplash.it/361/351?image=473');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Sonair', 8630369, 15, 495, 278, 'https://unsplash.it/278/495?image=481');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Regrant', 6568502, 13, 386, 298, 'https://unsplash.it/298/386?image=489');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Opela', 5925767, 6, 334, 322, 'https://unsplash.it/322/334?image=497');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Bytecard', 4210159, 8, 305, 219, 'https://unsplash.it/219/305?image=505');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Fixflex', 411890, 2, 340, 332, 'https://unsplash.it/332/340?image=513');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Job', 7012264, 14, 457, 351, 'https://unsplash.it/351/457?image=521');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Lotlux', 7858116, 14, 476, 283, 'https://unsplash.it/283/476?image=529');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Andalax', 8538379, 14, 305, 258, 'https://unsplash.it/258/305?image=537');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Asoka', 8959657, 8, 345, 247, 'https://unsplash.it/247/345?image=545');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Namfix', 1595573, 7, 345, 379, 'https://unsplash.it/379/345?image=553');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Tempsoft', 7242267, 11, 413, 313, 'https://unsplash.it/313/413?image=561');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Zaam-Dox', 2822134, 6, 376, 215, 'https://unsplash.it/215/376?image=569');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Konklab', 331134, 19, 358, 361, 'https://unsplash.it/361/358?image=577');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Mat Lam Tam', 772641, 5, 317, 360, 'https://unsplash.it/360/317?image=585');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Trippledex', 7743135, 16, 369, 217, 'https://unsplash.it/217/369?image=593');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Home Ing', 9259927, 19, 497, 222, 'https://unsplash.it/222/497?image=601');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Vagram', 8540896, 16, 454, 275, 'https://unsplash.it/275/454?image=609');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Otcom', 6037104, 2, 452, 294, 'https://unsplash.it/294/452?image=617');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Sub-Ex', 2374676, 10, 310, 336, 'https://unsplash.it/336/310?image=625');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Zaam-Dox', 620611, 18, 384, 336, 'https://unsplash.it/336/384?image=633');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Stronghold', 8074071, 8, 392, 224, 'https://unsplash.it/224/392?image=641');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Bitwolf', 7491256, 11, 397, 279, 'https://unsplash.it/279/397?image=649');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Keylex', 622244, 20, 442, 332, 'https://unsplash.it/332/442?image=657');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Temp', 1563434, 6, 418, 390, 'https://unsplash.it/390/418?image=665');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Zamit', 5803144, 13, 499, 316, 'https://unsplash.it/316/499?image=673');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Voyatouch', 7932032, 8, 325, 390, 'https://unsplash.it/390/325?image=681');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Gembucket', 7905358, 5, 394, 325, 'https://unsplash.it/325/394?image=689');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Zoolab', 4347518, 20, 362, 290, 'https://unsplash.it/290/362?image=697');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Alpha', 5162952, 7, 343, 377, 'https://unsplash.it/377/343?image=705');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Subin', 2591222, 18, 492, 368, 'https://unsplash.it/368/492?image=713');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Tresom', 8343038, 12, 380, 259, 'https://unsplash.it/259/380?image=721');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Trippledex', 6118914, 8, 453, 315, 'https://unsplash.it/315/453?image=729');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Span', 6368025, 19, 497, 314, 'https://unsplash.it/314/497?image=737');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Cookley', 149646, 19, 340, 328, 'https://unsplash.it/328/340?image=745');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Transcof', 1538724, 3, 368, 330, 'https://unsplash.it/330/368?image=753');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Sonsing', 4621300, 9, 323, 349, 'https://unsplash.it/349/323?image=761');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Tres-Zap', 2238321, 1, 381, 315, 'https://unsplash.it/315/381?image=769');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Y-find', 8513272, 11, 495, 314, 'https://unsplash.it/314/495?image=777');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Tresom', 4203076, 17, 413, 368, 'https://unsplash.it/368/413?image=785');
insert into ARTWORKENTITY (name, price, artist_id, height, width, image) values ('Rank', 2288823, 17, 417, 332, 'https://unsplash.it/332/417?image=793');




INSERT INTO CATEGORYENTITY(name) values('Ceramica');
INSERT INTO CATEGORYENTITY(name) values('Dibujo');
INSERT INTO CATEGORYENTITY(name) values('Escultura');
INSERT INTO CATEGORYENTITY(name) values('Grabado');
INSERT INTO CATEGORYENTITY(name) values('Mosaico');
INSERT INTO CATEGORYENTITY(name) values('Obra pictorica');




insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (1, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (2, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (3, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (4, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (5, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (6, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (7, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (8, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (9, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (10, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (11, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (12, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (13, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (14, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (15, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (16, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (17, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (18, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (19, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (20, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (21, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (22, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (23, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (24, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (25, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (26, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (27, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (28, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (29, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (30, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (31, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (32, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (33, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (34, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (35, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (36, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (37, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (38, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (39, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (40, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (41, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (42, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (43, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (44, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (45, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (46, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (47, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (48, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (49, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (50, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (51, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (52, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (53, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (54, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (55, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (56, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (57, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (58, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (59, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (60, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (61, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (62, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (63, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (64, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (65, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (66, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (67, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (68, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (69, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (70, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (71, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (72, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (73, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (74, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (75, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (76, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (77, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (78, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (79, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (80, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (81, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (82, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (83, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (84, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (85, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (86, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (87, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (88, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (89, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (90, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (91, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (92, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (93, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (94, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (95, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (96, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (97, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (98, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (99, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (100, 6);




insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', null, 100);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', null, 53);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras in purus eu magna vulputate luctus.', null, 22);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Phasellus in felis.', null, 2);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aliquam non mauris. Morbi non lectus.', null, 68);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec ut dolor.', null, 12);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', null, 49);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', null, 24);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce consequat. Nulla nisl.', null, 7);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', null, 73);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nam nulla.', null, 16);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', null, 75);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aliquam erat volutpat. In congue.', null, 96);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aliquam non mauris. Morbi non lectus.', null, 72);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', null, 66);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', null, 22);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', null, 5);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', null, 4);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', null, 100);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', null, 100);
insert into COMMENTENTITY (comment, name, artwork_id) values ('In hac habitasse platea dictumst.', null, 69);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aenean lectus. Pellentesque eget nunc.', null, 14);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent id massa id nisl venenatis lacinia.', null, 89);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent id massa id nisl venenatis lacinia.', null, 78);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', null, 57);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent blandit. Nam nulla.', null, 76);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', null, 47);
insert into COMMENTENTITY (comment, name, artwork_id) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna.', null, 82);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', null, 64);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', null, 43);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Etiam pretium iaculis justo. In hac habitasse platea dictumst.', null, 8);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Mauris lacinia sapien quis libero.', null, 13);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus vel nulla eget eros elementum pellentesque.', null, 28);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis mattis egestas metus. Aenean fermentum.', null, 13);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', null, 16);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', null, 71);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Maecenas rhoncus aliquam lacus.', null, 33);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', null, 48);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce consequat.', null, 10);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', null, 2);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Etiam pretium iaculis justo. In hac habitasse platea dictumst.', null, 53);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Pellentesque ultrices mattis odio. Donec vitae nisi.', null, 29);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec dapibus.', null, 59);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nulla mollis molestie lorem. Quisque ut erat.', null, 10);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', null, 12);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Maecenas pulvinar lobortis est.', null, 35);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras non velit nec nisi vulputate nonummy.', null, 19);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', null, 97);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nulla mollis molestie lorem.', null, 75);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce posuere felis sed lacus.', null, 75);
insert into COMMENTENTITY (comment, name, artwork_id) values ('In hac habitasse platea dictumst.', null, 100);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Phasellus in felis.', null, 7);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis consequat dui nec nisi volutpat eleifend.', null, 53);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', null, 47);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec semper sapien a libero. Nam dui.', null, 91);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', null, 35);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', null, 30);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', null, 80);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', null, 87);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras pellentesque volutpat dui.', null, 35);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', null, 82);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', null, 80);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Ut tellus.', null, 54);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', null, 48);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent blandit lacinia erat.', null, 17);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', null, 22);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nam nulla.', null, 1);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus tortor. Duis mattis egestas metus.', null, 92);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Suspendisse potenti.', null, 94);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nulla suscipit ligula in lacus.', null, 14);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi quis tortor id nulla ultrices aliquet.', null, 93);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec quis orci eget orci vehicula condimentum.', null, 57);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', null, 17);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum rutrum rutrum neque.', null, 10);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent blandit. Nam nulla.', null, 55);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce consequat. Nulla nisl.', null, 1);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec semper sapien a libero.', null, 95);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec posuere metus vitae ipsum. Aliquam non mauris.', null, 40);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Quisque ut erat.', null, 28);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras in purus eu magna vulputate luctus.', null, 53);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', null, 1);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Suspendisse potenti.', null, 73);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi a ipsum. Integer a nibh.', null, 95);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus vestibulum sagittis sapien.', null, 8);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', null, 54);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Phasellus sit amet erat.', null, 49);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', null, 58);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer ac neque. Duis bibendum.', null, 2);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Etiam vel augue.', null, 49);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', null, 17);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', null, 45);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Sed accumsan felis. Ut at dolor quis odio consequat varius.', null, 21);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', null, 75);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis at velit eu est congue elementum.', null, 93);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Suspendisse potenti. Nullam porttitor lacus at turpis.', null, 48);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Etiam justo. Etiam pretium iaculis justo.', null, 80);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', null, 9);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', null, 22);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Pellentesque viverra pede ac diam.', null, 70);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Ut at dolor quis odio consequat varius.', null, 2);


insert into cliententity values(1,'test');
insert into cliententity values(101,'cliente');




insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 1);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 2);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 3);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 4);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 5);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 6);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 7);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 8);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 9);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 10);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 11);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 12);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 13);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 14);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 15);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 16);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 17);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 18);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 19);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 20);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 21);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 22);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 23);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 24);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 25);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 26);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 27);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 28);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 29);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 30);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 31);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 32);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 33);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 34);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 35);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 36);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 37);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 38);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 39);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 40);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 41);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 42);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 43);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 44);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 45);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 46);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 47);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 48);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 49);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 50);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 51);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 52);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 53);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 54);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 55);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 56);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 57);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 58);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 59);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 60);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 61);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 62);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 63);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 64);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 65);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 66);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 67);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 68);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 69);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 70);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 71);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 72);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 73);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 74);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 75);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 76);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 77);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 78);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 79);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 80);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 81);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 82);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 83);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 84);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 85);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 86);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 87);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 88);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 89);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 90);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 91);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 92);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 93);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 94);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 95);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 96);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 97);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 98);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 99);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 100);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 1);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 2);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 3);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 4);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 5);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 6);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 7);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 8);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 9);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 10);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 11);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 12);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 13);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 14);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 15);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 16);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 17);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 18);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 19);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 20);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 21);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 22);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 23);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 24);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 25);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 26);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 27);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 28);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 29);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 30);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 31);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 32);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 33);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 34);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 35);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 36);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 37);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 38);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 39);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 40);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 41);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 42);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 43);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 44);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 45);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 46);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 47);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 48);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 49);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 50);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 51);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 52);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 53);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 54);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 55);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 56);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 57);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 58);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 59);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 60);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 61);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 62);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 63);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 64);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 65);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 66);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 67);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 68);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 69);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 70);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 71);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 72);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 73);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 74);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 75);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 76);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 77);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 78);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 79);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 80);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 81);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 82);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 83);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 84);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 85);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 86);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 87);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 88);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 89);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 90);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 91);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 92);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 93);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 94);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 95);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 96);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 97);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 98);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 99);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 100);
