insert into ARTISTENTITY (name, username) values ('Cynthia Hamilton','artist1');
insert into ARTISTENTITY (name, username) values ('Harold Moreno','artist2');
insert into ARTISTENTITY (name, username) values ('Virginia Cunningham','artist3');
insert into ARTISTENTITY (name, username) values ('Patrick Bailey','artist4');
insert into ARTISTENTITY (name, username) values ('Judith Matthews','artist5');
insert into ARTISTENTITY (name, username) values ('Jacqueline White','artist6');
insert into ARTISTENTITY (name, username) values ('Gloria Henderson','artist7');
insert into ARTISTENTITY (name, username) values ('Robert Gibson','artist8');
insert into ARTISTENTITY (name, username) values ('Jennifer Gomez','artist9');
insert into ARTISTENTITY (name, username) values ('Robin Gomez','artist10');


insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-10-03 01:29:26', 'Bitchip', 9475463, 10, 381, 293, 'https://unsplash.it/293/381?image=1');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-22 02:28:46', 'Hatity', 6238472, 1, 316, 323, 'https://unsplash.it/323/316?image=9');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-10-27 18:47:16', 'Fix San', 7776143, 4, 411, 247, 'https://unsplash.it/247/411?image=17');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-04-07 12:44:10', 'Kanlam', 7428821, 2, 321, 262, 'https://unsplash.it/262/321?image=25');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-09-28 11:08:20', 'Holdlamis', 9385821, 9, 304, 257, 'https://unsplash.it/257/304?image=33');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-07-01 16:35:14', 'Flowdesk', 5687732, 8, 495, 253, 'https://unsplash.it/253/495?image=41');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-10-28 19:06:06', 'Aerified', 2160592, 8, 485, 360, 'https://unsplash.it/360/485?image=49');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-06-27 11:46:58', 'Flowdesk', 2044894, 7, 331, 364, 'https://unsplash.it/364/331?image=57');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-07-27 06:40:33', 'Zamit', 4780872, 1, 351, 298, 'https://unsplash.it/298/351?image=65');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-06-13 18:05:39', 'Voltsillam', 9405265, 5, 306, 277, 'https://unsplash.it/277/306?image=73');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-03-23 22:46:29', 'Holdlamis', 3030367, 6, 402, 244, 'https://unsplash.it/244/402?image=81');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-10-10 17:47:10', 'Temp', 1155667, 2, 407, 244, 'https://unsplash.it/244/407?image=89');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-04 04:57:23', 'Transcof', 148224, 1, 342, 363, 'https://unsplash.it/363/342?image=97');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-18 07:37:53', 'Veribet', 5997791, 4, 359, 229, 'https://unsplash.it/229/359?image=105');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-06 22:31:54', 'Greenlam', 3818199, 3, 364, 331, 'https://unsplash.it/331/364?image=113');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-01-26 14:53:55', 'Bytecard', 8808722, 5, 443, 337, 'https://unsplash.it/337/443?image=121');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-03-20 23:52:36', 'Home Ing', 6097023, 5, 360, 313, 'https://unsplash.it/313/360?image=129');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-06-11 04:41:33', 'Redhold', 6253395, 6, 382, 395, 'https://unsplash.it/395/382?image=137');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-08-31 05:07:05', 'Stim', 7631894, 6, 306, 307, 'https://unsplash.it/307/306?image=145');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-07-25 18:53:11', 'Vagram', 812893, 3, 363, 346, 'https://unsplash.it/346/363?image=153');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-06-16 17:33:44', 'Toughjoyfax', 6248407, 2, 479, 286, 'https://unsplash.it/286/479?image=161');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-03-28 02:33:18', 'Fintone', 6983354, 10, 480, 313, 'https://unsplash.it/313/480?image=169');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-06-06 22:04:57', 'Cardguard', 6486223, 2, 404, 277, 'https://unsplash.it/277/404?image=177');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-06-19 10:31:56', 'Sonair', 7147884, 8, 452, 230, 'https://unsplash.it/230/452?image=185');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-02-04 10:54:02', 'Home Ing', 1544294, 9, 324, 385, 'https://unsplash.it/385/324?image=193');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-09 04:16:57', 'Mat Lam Tam', 9844635, 2, 321, 370, 'https://unsplash.it/370/321?image=201');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-09-26 13:19:50', 'Lotstring', 7669987, 5, 415, 250, 'https://unsplash.it/250/415?image=209');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-18 07:08:05', 'Andalax', 6563302, 4, 436, 279, 'https://unsplash.it/279/436?image=217');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-08-17 04:59:45', 'Bytecard', 6020730, 2, 485, 219, 'https://unsplash.it/219/485?image=225');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-16 20:12:45', 'Lotstring', 4290259, 1, 433, 207, 'https://unsplash.it/207/433?image=233');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-15 21:06:32', 'Viva', 2556809, 2, 343, 304, 'https://unsplash.it/304/343?image=241');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-04-25 17:49:38', 'Latlux', 4847054, 9, 313, 212, 'https://unsplash.it/212/313?image=249');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-07-31 21:22:37', 'Span', 8925319, 4, 490, 289, 'https://unsplash.it/289/490?image=257');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-10-20 11:22:32', 'Voltsillam', 7620452, 10, 301, 270, 'https://unsplash.it/270/301?image=265');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-10-06 23:02:24', 'Y-Solowarm', 1231419, 3, 336, 285, 'https://unsplash.it/285/336?image=273');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-09 09:02:34', 'Aerified', 990024, 6, 345, 397, 'https://unsplash.it/397/345?image=281');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-05 10:53:30', 'Rank', 5865105, 10, 491, 366, 'https://unsplash.it/366/491?image=289');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-09-26 03:02:36', 'Sub-Ex', 9305786, 10, 426, 327, 'https://unsplash.it/327/426?image=297');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-09-17 01:16:09', 'Kanlam', 2678940, 10, 394, 258, 'https://unsplash.it/258/394?image=305');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-06 17:31:02', 'Stim', 8217264, 4, 423, 312, 'https://unsplash.it/312/423?image=313');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-01-17 12:38:58', 'Fixflex', 6714624, 5, 320, 259, 'https://unsplash.it/259/320?image=321');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-02-27 22:10:42', 'Home Ing', 9243870, 10, 449, 285, 'https://unsplash.it/285/449?image=329');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-04-05 01:40:15', 'Kanlam', 2892589, 9, 355, 242, 'https://unsplash.it/242/355?image=337');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-15 11:24:14', 'Ronstring', 3530185, 9, 458, 369, 'https://unsplash.it/369/458?image=345');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-08-19 03:35:54', 'Bytecard', 1436416, 9, 360, 254, 'https://unsplash.it/254/360?image=353');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-07-13 07:09:27', 'Zaam-Dox', 6545257, 10, 398, 391, 'https://unsplash.it/391/398?image=361');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-02-04 14:36:47', 'Overhold', 4135517, 9, 357, 289, 'https://unsplash.it/289/357?image=369');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-03-28 04:38:41', 'Viva', 1729928, 9, 405, 254, 'https://unsplash.it/254/405?image=377');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-03-28 11:00:59', 'Zathin', 2259560, 10, 357, 349, 'https://unsplash.it/349/357?image=385');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-07 17:33:19', 'Toughjoyfax', 619641, 7, 320, 365, 'https://unsplash.it/365/320?image=393');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-01-13 08:58:46', 'Bigtax', 8145006, 3, 454, 240, 'https://unsplash.it/240/454?image=401');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-20 04:12:57', 'Bytecard', 2292080, 6, 409, 287, 'https://unsplash.it/287/409?image=409');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-02-03 02:30:01', 'Hatity', 1713238, 3, 324, 262, 'https://unsplash.it/262/324?image=417');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-13 23:14:26', 'Asoka', 6338570, 2, 360, 304, 'https://unsplash.it/304/360?image=425');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-27 10:25:33', 'Zathin', 1304043, 3, 450, 339, 'https://unsplash.it/339/450?image=433');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-02-18 02:23:10', 'Aerified', 5756782, 3, 308, 349, 'https://unsplash.it/349/308?image=441');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-07-07 20:25:31', 'Zaam-Dox', 9472728, 3, 390, 280, 'https://unsplash.it/280/390?image=449');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-08-12 23:55:52', 'Regrant', 9786460, 3, 393, 392, 'https://unsplash.it/392/393?image=457');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-04-01 07:22:20', 'Lotlux', 8995937, 1, 498, 222, 'https://unsplash.it/222/498?image=465');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-08-18 22:29:04', 'It', 4771063, 5, 490, 347, 'https://unsplash.it/347/490?image=473');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-02-24 22:07:28', 'Domainer', 5468557, 5, 334, 313, 'https://unsplash.it/313/334?image=481');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-04-14 07:06:52', 'Duobam', 7026651, 9, 480, 303, 'https://unsplash.it/303/480?image=489');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-06-25 14:56:39', 'Kanlam', 1426123, 2, 414, 235, 'https://unsplash.it/235/414?image=497');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-18 06:38:20', 'Bitwolf', 9237873, 8, 393, 294, 'https://unsplash.it/294/393?image=505');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-01 15:05:42', 'Fix San', 7521663, 4, 368, 257, 'https://unsplash.it/257/368?image=513');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-08-25 10:05:20', 'Duobam', 9664618, 10, 312, 311, 'https://unsplash.it/311/312?image=521');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-16 23:27:52', 'Andalax', 7600748, 10, 448, 300, 'https://unsplash.it/300/448?image=529');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-07 03:55:12', 'Andalax', 7980297, 10, 379, 299, 'https://unsplash.it/299/379?image=537');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-07 02:20:24', 'Holdlamis', 9585032, 3, 381, 272, 'https://unsplash.it/272/381?image=545');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-03-31 09:35:09', 'Zaam-Dox', 1620846, 4, 448, 228, 'https://unsplash.it/228/448?image=553');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-04-24 08:55:16', 'Bitwolf', 9036160, 10, 393, 251, 'https://unsplash.it/251/393?image=561');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-01-28 19:15:06', 'Konklux', 8596892, 9, 375, 218, 'https://unsplash.it/218/375?image=569');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-06-28 16:37:29', 'Prodder', 8421871, 10, 476, 343, 'https://unsplash.it/343/476?image=577');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-07-14 14:43:54', 'Treeflex', 2771032, 10, 400, 236, 'https://unsplash.it/236/400?image=585');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-08-18 05:41:48', 'Fixflex', 2383734, 8, 365, 394, 'https://unsplash.it/394/365?image=593');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-03-25 00:17:56', 'Bigtax', 1776900, 8, 320, 252, 'https://unsplash.it/252/320?image=601');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-01-21 06:23:05', 'Duobam', 6079053, 1, 353, 218, 'https://unsplash.it/218/353?image=609');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-06-11 08:14:55', 'Matsoft', 4883383, 8, 319, 379, 'https://unsplash.it/379/319?image=617');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-19 07:46:57', 'Zontrax', 6741375, 4, 437, 213, 'https://unsplash.it/213/437?image=625');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-09-17 00:07:31', 'Rank', 4234110, 5, 425, 328, 'https://unsplash.it/328/425?image=633');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-11 21:42:53', 'Kanlam', 4370689, 8, 457, 314, 'https://unsplash.it/314/457?image=641');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-15 15:33:42', 'Tin', 5580532, 10, 402, 268, 'https://unsplash.it/268/402?image=649');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-08-03 06:39:12', 'Konklux', 2750350, 7, 335, 337, 'https://unsplash.it/337/335?image=657');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-03-24 21:08:15', 'Alpha', 1845901, 8, 441, 324, 'https://unsplash.it/324/441?image=665');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-07-31 22:10:08', 'Quo Lux', 5425277, 5, 398, 371, 'https://unsplash.it/371/398?image=673');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-22 09:50:40', 'Rank', 181255, 2, 324, 384, 'https://unsplash.it/384/324?image=681');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-06-24 14:11:39', 'Opela', 7998645, 8, 440, 331, 'https://unsplash.it/331/440?image=689');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-25 15:49:00', 'Viva', 8720857, 2, 349, 216, 'https://unsplash.it/216/349?image=697');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-09-04 23:28:39', 'Job', 3232007, 2, 333, 263, 'https://unsplash.it/263/333?image=705');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-02-21 20:20:03', 'Sonsing', 7879670, 3, 411, 348, 'https://unsplash.it/348/411?image=713');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-10-20 20:10:22', 'Redhold', 9189462, 8, 470, 257, 'https://unsplash.it/257/470?image=721');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-08-07 19:41:32', 'Stim', 3015293, 6, 451, 204, 'https://unsplash.it/204/451?image=729');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-19 23:43:43', 'Kanlam', 1426508, 9, 498, 395, 'https://unsplash.it/395/498?image=737');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-04 17:59:57', 'Bamity', 3463756, 5, 468, 279, 'https://unsplash.it/279/468?image=780');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-19 17:32:34', 'Temp', 5564260, 1, 345, 283, 'https://unsplash.it/283/345?image=755');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-18 11:19:09', 'Keylex', 2472957, 7, 338, 359, 'https://unsplash.it/359/338?image=761');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-10-06 01:16:42', 'Hatity', 6458192, 5, 473, 263, 'https://unsplash.it/263/473?image=769');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-20 23:59:42', 'Mat Lam Tam', 4910773, 4, 353, 289, 'https://unsplash.it/289/353?image=777');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-11-05 15:12:31', 'Gembucket', 1777615, 7, 452, 211, 'https://unsplash.it/211/452?image=785');
insert into ARTWORKENTITY (dateadded, name, price, artist_id, height, width, image) values ('2016-05-02 19:12:17', 'Sonsing', 720052, 2, 385, 400, 'https://unsplash.it/400/385?image=793');




INSERT INTO CATEGORYENTITY(name) values('Ceramica');
INSERT INTO CATEGORYENTITY(name) values('Dibujo');
INSERT INTO CATEGORYENTITY(name) values('Escultura');
INSERT INTO CATEGORYENTITY(name) values('Grabado');
INSERT INTO CATEGORYENTITY(name) values('Mosaico');
INSERT INTO CATEGORYENTITY(name) values('Obra pictorica');




insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (1, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (2, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (3, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (4, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (5, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (6, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (7, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (8, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (9, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (10, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (11, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (12, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (13, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (14, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (15, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (16, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (17, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (18, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (19, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (20, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (21, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (22, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (23, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (24, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (25, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (26, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (27, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (28, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (29, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (30, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (31, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (32, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (33, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (34, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (35, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (36, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (37, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (38, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (39, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (40, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (41, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (42, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (43, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (44, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (45, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (46, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (47, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (48, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (49, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (50, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (51, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (52, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (53, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (54, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (55, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (56, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (57, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (58, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (59, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (60, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (61, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (62, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (63, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (64, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (65, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (66, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (67, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (68, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (69, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (70, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (71, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (72, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (73, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (74, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (75, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (76, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (77, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (78, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (79, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (80, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (81, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (82, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (83, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (84, 4);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (85, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (86, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (87, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (88, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (89, 6);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (90, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (91, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (92, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (93, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (94, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (95, 3);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (96, 1);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (97, 2);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (98, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (99, 5);
insert into ARTWORKENTITY_CATEGORYENTITY (artworkentity_id, category_id) values (100, 6);




insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', null, 100);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', null, 53);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras in purus eu magna vulputate luctus.', null, 22);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Phasellus in felis.', null, 2);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aliquam non mauris. Morbi non lectus.', null, 68);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec ut dolor.', null, 12);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', null, 49);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', null, 24);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce consequat. Nulla nisl.', null, 7);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', null, 73);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nam nulla.', null, 16);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', null, 75);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aliquam erat volutpat. In congue.', null, 96);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aliquam non mauris. Morbi non lectus.', null, 72);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', null, 66);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', null, 22);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', null, 5);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', null, 4);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', null, 100);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', null, 100);
insert into COMMENTENTITY (comment, name, artwork_id) values ('In hac habitasse platea dictumst.', null, 69);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aenean lectus. Pellentesque eget nunc.', null, 14);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent id massa id nisl venenatis lacinia.', null, 89);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent id massa id nisl venenatis lacinia.', null, 78);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', null, 57);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent blandit. Nam nulla.', null, 76);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', null, 47);
insert into COMMENTENTITY (comment, name, artwork_id) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna.', null, 82);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', null, 64);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', null, 43);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Etiam pretium iaculis justo. In hac habitasse platea dictumst.', null, 8);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Mauris lacinia sapien quis libero.', null, 13);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus vel nulla eget eros elementum pellentesque.', null, 28);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis mattis egestas metus. Aenean fermentum.', null, 13);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', null, 16);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', null, 71);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Maecenas rhoncus aliquam lacus.', null, 33);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', null, 48);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce consequat.', null, 10);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', null, 2);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Etiam pretium iaculis justo. In hac habitasse platea dictumst.', null, 53);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Pellentesque ultrices mattis odio. Donec vitae nisi.', null, 29);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec dapibus.', null, 59);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nulla mollis molestie lorem. Quisque ut erat.', null, 10);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', null, 12);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Maecenas pulvinar lobortis est.', null, 35);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras non velit nec nisi vulputate nonummy.', null, 19);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', null, 97);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nulla mollis molestie lorem.', null, 75);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce posuere felis sed lacus.', null, 75);
insert into COMMENTENTITY (comment, name, artwork_id) values ('In hac habitasse platea dictumst.', null, 100);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Phasellus in felis.', null, 7);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis consequat dui nec nisi volutpat eleifend.', null, 53);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', null, 47);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec semper sapien a libero. Nam dui.', null, 91);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', null, 35);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', null, 30);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', null, 80);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', null, 87);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras pellentesque volutpat dui.', null, 35);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', null, 82);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', null, 80);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Ut tellus.', null, 54);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', null, 48);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent blandit lacinia erat.', null, 17);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', null, 22);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nam nulla.', null, 1);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus tortor. Duis mattis egestas metus.', null, 92);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Suspendisse potenti.', null, 94);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Nulla suscipit ligula in lacus.', null, 14);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi quis tortor id nulla ultrices aliquet.', null, 93);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec quis orci eget orci vehicula condimentum.', null, 57);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', null, 17);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum rutrum rutrum neque.', null, 10);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Praesent blandit. Nam nulla.', null, 55);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Fusce consequat. Nulla nisl.', null, 1);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec semper sapien a libero.', null, 95);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec posuere metus vitae ipsum. Aliquam non mauris.', null, 40);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Quisque ut erat.', null, 28);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cras in purus eu magna vulputate luctus.', null, 53);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', null, 1);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Suspendisse potenti.', null, 73);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi a ipsum. Integer a nibh.', null, 95);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vivamus vestibulum sagittis sapien.', null, 8);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', null, 54);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Phasellus sit amet erat.', null, 49);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', null, 58);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer ac neque. Duis bibendum.', null, 2);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Etiam vel augue.', null, 49);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', null, 17);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', null, 45);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Sed accumsan felis. Ut at dolor quis odio consequat varius.', null, 21);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', null, 75);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Duis at velit eu est congue elementum.', null, 93);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Suspendisse potenti. Nullam porttitor lacus at turpis.', null, 48);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Etiam justo. Etiam pretium iaculis justo.', null, 80);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', null, 9);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', null, 22);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Pellentesque viverra pede ac diam.', null, 70);
insert into COMMENTENTITY (comment, name, artwork_id) values ('Ut at dolor quis odio consequat varius.', null, 2);


insert into cliententity values(1,'test');
insert into cliententity values(101,'cliente');




insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 1);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 2);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 3);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 4);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 5);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 6);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 7);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 8);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 9);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 10);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 11);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 12);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 13);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 14);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 15);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 16);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 17);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 18);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 19);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 20);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 21);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 22);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 23);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 24);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 25);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 26);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 27);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 28);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 29);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 30);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 31);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 32);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 33);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 34);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 35);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 36);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 37);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 38);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 39);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 40);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 41);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 42);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 43);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 44);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 45);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 46);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 47);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 48);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 49);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 50);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 51);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 52);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 53);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 54);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 55);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 56);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 57);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 58);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 59);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 60);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 61);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 62);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 63);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 64);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 65);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 66);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 67);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 68);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 69);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 70);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 71);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 72);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 73);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 74);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 75);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 76);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 77);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 78);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 79);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 80);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 81);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 82);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 83);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'cliente2@cliente.com', 84);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 85);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 86);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 87);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 88);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 89);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 90);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 91);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 92);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 93);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'cliente2@cliente.com', 94);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 95);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 96);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 97);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'cliente2@cliente.com', 98);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'cliente2@cliente.com', 99);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'cliente2@cliente.com', 100);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 1);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 2);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 3);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 4);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 5);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 6);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 7);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 8);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 9);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 10);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 11);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 12);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 13);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 14);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 15);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 16);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 17);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 18);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 19);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 20);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 21);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 22);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 23);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 24);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 25);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 26);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 27);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 28);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 29);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 30);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 31);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 32);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 33);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 34);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 35);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 36);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 37);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 38);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 39);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 40);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 41);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 42);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 43);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 44);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 45);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 46);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 47);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 48);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 49);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 50);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 51);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 52);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 53);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 54);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 55);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 56);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 57);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 58);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 59);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 60);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 61);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 62);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 63);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 64);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 65);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 66);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 67);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 68);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 69);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 70);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 71);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 72);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 73);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 74);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 75);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 76);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 77);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 78);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 79);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 80);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 81);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 82);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 83);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 84);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 85);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 86);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 87);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 88);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 3, 'lc.diaz12@uniandes.edu.co', 89);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 90);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 91);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 92);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 93);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 94);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 95);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 96);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 2, 'lc.diaz12@uniandes.edu.co', 97);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 1, 'lc.diaz12@uniandes.edu.co', 98);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 5, 'lc.diaz12@uniandes.edu.co', 99);
insert into QUALIFICATIONENTITY (name, qualification, userclient, artwork_id) values (null, 4, 'lc.diaz12@uniandes.edu.co', 100);